### ISSUE TITLE
JetBrains IDEs

### ISSUE THREAD

**Issue by mdragoss** [KElee01/macos-icons#2]
First of all want to thanks for your work.

Could you please make the same icons style for all JB IDEs? Will be great all JB IDEs the same icons style look. 
**DataGrip**, **Rider**, **Ruby**

<img width="144" alt="Screenshot 2022-06-29 at 22 51 30" src="https://user-images.githubusercontent.com/46487312/176531472-deab6944-3cf5-4e8e-9aac-9b8dc37a1b60.png">

**Comment by stevelgs** [comment]
and CLion

**Comment by KElee01** [comment]
@De0cruz @mdragossh Finally, I've uploaded most of the JetBrains apps' icons, you can find them [here](https://github.com/KElee01/macos-icons/tree/main/JetBrains%20Suite), hope you guys like it!

**Comment by mdragoss** [comment]
Thanks a lot!
