### ISSUE TITLE
Jetbrain Gateway Icon

### ISSUE THREAD

**Issue by liafonx** [KElee01/macos-icons#4]
Hi Kama, 
I really like your Jetbrains icon set! Amazing job!
It would be better if the icon of Gateway can be added in the icon set, which looks like:
<img width="403" alt="image" src="https://github.com/KElee01/macos-icons/assets/79797050/cb73feec-8865-4da3-94ba-6a0d1c6b868a">
and this is its offical webpage: https://www.jetbrains.com/remote-development/gateway/

**Comment by KElee01** [comment]
Thanks for the love! I've added the Gateway icons to the JetBrains set. You can also have the PNG files here:
![Gateway](https://github.com/KElee01/macos-icons/assets/54350573/f3e7ed3a-bb20-47fd-88c9-97cf24ac8448)
![Gateway_alt](https://github.com/KElee01/macos-icons/assets/54350573/9cc91822-bd81-494e-bddc-e2733270aba3)

Hope you like them. Appreciate your support!

**Comment by liafonx** [comment]
Thank you! I really like it 🥰
